/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supplier_management_system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DUL
 */
public class conform_suppliers_update extends javax.swing.JFrame {
    
    
    ResultSet rs=null;
    PreparedStatement pst=null;
    String query;
    private int supplieID;
    private String supplierName;
    private String nic;
    private int company_contact;
    private String supplier_contact;
    private String company_name;
    private String supplier_email;
    Connection con=null;
    DBconnect DB=new DBconnect();
    /**
     * Creates new form conform_suppliers_update
     */
    public conform_suppliers_update() {
        initComponents();
        con=DBconnect.connect();
    }
    
   /* public  conform_suppliers_update(int supplirID, String supplierName, String nic,int Comp_contact, String supp_contact,String comp_name,String supp_email){
     this.supplieID=supplirID;
     this
    }*/

    public conform_suppliers_update(int supplieID, String supplierName, String nic, int company_contact, String supplier_contact, String company_name, String supplier_email) {
        initComponents();
        con=DBconnect.connect();
        
        this.supplieID = supplieID;
        this.supplierName = supplierName;
        this.nic = nic;
        this.company_contact = company_contact;
        this.supplier_contact = supplier_contact;
        this.company_name = company_name;
        this.supplier_email = supplier_email;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        user_name = new javax.swing.JTextField();
        conform2_updatesuppliers = new javax.swing.JButton();
        conform2_updatesuppliers1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WARNING !!!");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONFORM UPDATE THIS SUPPLIER !!!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("PASSWORD:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("NAME:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, -1));

        password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(password_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 180, -1));

        user_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_nameActionPerformed(evt);
            }
        });
        getContentPane().add(user_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 180, -1));

        conform2_updatesuppliers.setText("SAFETY GO BACK");
        conform2_updatesuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conform2_updatesuppliersActionPerformed(evt);
            }
        });
        getContentPane().add(conform2_updatesuppliers, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 140, -1));

        conform2_updatesuppliers1.setText("CONFORM !!!");
        conform2_updatesuppliers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conform2_updatesuppliers1ActionPerformed(evt);
            }
        });
        getContentPane().add(conform2_updatesuppliers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 140, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supplier_management_system/subbbbbb.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 410, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_fieldActionPerformed

    private void user_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_nameActionPerformed

    private void conform2_updatesuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conform2_updatesuppliersActionPerformed
        suppliersx d1=new suppliersx();
        setVisible(true);
        this.dispose();
    }//GEN-LAST:event_conform2_updatesuppliersActionPerformed

    private void conform2_updatesuppliers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conform2_updatesuppliers1ActionPerformed
        
        String username=user_name.getText();
        String password=String.valueOf(password_field.getPassword());
        try {
          this.query="SELECT * FROM `login` where username='"+username+"' and password='"+password+"'";
          pst=con.prepareStatement(query);  
          rs=pst.executeQuery();
          
          
          if(rs.next()){
              this.query="UPDATE `supplier` SET `supplier_Name`='"+this.supplierName+"',`supplier_email`='"+this.supplier_email+"',`contact_perspn`='"+this.supplier_contact+"',`contact_tel_number`='"+this.company_contact+"',`CompanyName`='"+this.company_name+"',`SupNIC`='"+this.nic+"' WHERE supplier_Id ='"+this.supplieID+"'";
              pst=con.prepareStatement(query);  
               pst.executeUpdate();
               this.dispose();
          }
          else{
              JOptionPane.showMessageDialog(this, "Invlid Autountications");
          }
          
        } catch (SQLException ex) {
            Logger.getLogger(conform_suppliers_update.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
                
        
    }//GEN-LAST:event_conform2_updatesuppliers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conform_suppliers_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conform_suppliers_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conform_suppliers_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conform_suppliers_update.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conform_suppliers_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conform2_updatesuppliers;
    private javax.swing.JButton conform2_updatesuppliers1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
